before_script:
# Install dependencies
- bash ci/docker_install.sh > /dev/null

# We test PHP7.3 (good luck with that)
test:7.3:
  image: php:7.3
  script:
  - phpunit --configuration phpunit_myapp.xml